### ISSUE TITLE
Backward compatibility for android 4.x

### ISSUE THREAD

**Issue by cs17899219** [shadowsocks/shadowsocks-android#1038]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment
Android 4.3

### Configuration
Nope

### What did you do?
Install Shadowsocks via Google Play Store

### What did you expect to see?
the latest available version of Shadowsocks  is v3.0.4 

### What did you see instead?

Since latest release Shadowsocks-Android 3.4.0 introduced a lot of bugfixes ,UI improvement and features.
Is that possible continue to support running on Android 4.1+(Jelly Bean) there by many smartphone still run on this version in some region.

thanks

**Comment by Mygod** [comment]
Support was dropped for a reason.

**Comment by Mygod** [comment]
Btw one can back port 3.4.0 back to Android 4.0 (which accounts for ~7.2% of the users) but that requires at least quite some effort. Back porting to a lower version would require even more effort since that would also break this app's dependencies. But back porting PRs will NOT get merged and we strongly encourage everyone to update their Android system.

**Comment by cs17899219** [comment]
Sure.
It looks unnecessary If back porting PRs would never merge into trunk .

Thanks also.
