### ISSUE TITLE
升级到8.1后，wifi情况下开启ss后，设备判定是没有使用wlan网络。

### ISSUE THREAD

**Issue by 890604** [shadowsocks/shadowsocks-android#1501]
升级到8.1后，wifi情况下开启ss后，设备判定是没有使用wlan网络，导致一些需要wlan自动下载备份的功能无法使用。升级以前没有问题的。
### Environment

* Android version: 8.1
* Device: nexus6p
* Shadowsocks version: 4.2.5

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
升级到8.1后，wifi情况下开启ss后，设备判定是没有使用wlan网络，导致一些需要wlan自动下载备份的功能无法使用。例如：没有升级前我设置的应用商店在wlan连接下自动更新，在升级之后就无法自动更新，并且提示没有连接到wlan网络。

**Comment by iKirby** [comment]
这是 Android 8.1.0 系统自身的问题，请参考 https://issuetracker.google.com/issues/70125374

**Comment by rxwangwb** [comment]
有解决办法了吗

**Comment by 890604** [comment]
目前没有解决方案，只能在路由上安装ss插件
________________________________
发件人: Michael <notifications@github.com>
发送时间: 2018年1月23日 22:49
收件人: shadowsocks/shadowsocks-android
抄送: 890604; Author
主题: Re: [shadowsocks/shadowsocks-android] 升级到8.1后，wifi情况下开启ss后，设备判定是没有使用wlan网络。 (#1501)


有解决办法了吗

―

**Comment by qianjinhui** [comment]
截至3月5号补丁，问题依然存在。

**Comment by sbmzhcn** [comment]
same issue. 小米6x MIUI 9.5 稳定版 ，问题依旧

**Comment by chenshaoju** [comment]
This issue has fixed by Google, LineageOS has to Merge this path, And confirmed at LineageOS 15.1 20180813 version.
此问题已经经由Google修复，LineageOS已经合并了此补丁，并在LineageOS 15.1 20180813 中确认。

For more information, Please read:
若需了解详情，请阅读以下内容：
https://review.lineageos.org/#/c/LineageOS/android_frameworks_opt_telephony/+/222660/
https://review.lineageos.org/#/c/LineageOS/android_frameworks_base/+/222655/
https://review.lineageos.org/#/c/LineageOS/android_frameworks_base/+/222657/

![image](https://user-images.githubusercontent.com/515763/44132498-b422f2f6-a08c-11e8-8b3c-2356b3b52f52.png)

**Comment by Mygod** [comment]
Thanks. [This fix](https://android.googlesource.com/platform/frameworks/base.git/+/97e1cd61d3040dd366ac9e25cdb6f134c7490846) seems to be available since [android-8.1.0_r42](https://android.googlesource.com/platform/frameworks/base.git/+/android-8.1.0_r42), tagged on Jul 20. This change is specific to Android 8.1.
