### ISSUE TITLE
Questions about Custom Rules

### ISSUE THREAD

**Issue by AnyoeDove** [shadowsocks/shadowsocks-android#1505]
1. About remote ACL file in custom rule, is it support the ACL file starts from "[proxy_all]"? Everytime my remote ACL file was modified to the file start from "[bypass_all]" after start shadowsocks-android. Maybe just leave the ACL file alone and don't change it?
BTW Android 6.0.1, armv7, Shadowsocks-Android v4.4.0

2. About [outbound_block_list], still [Only IP is allowed, *NOT* domain name.](https://github.com/shadowsocks/shadowsocks-libev/blob/master/acl/server_block_chn.acl#L2) ?

3. My ACL file looks like this:
```
[proxy_all]
[outbound_block_list]
11.22.33.44/22
....
[bypass_list]
(^|\.)a\.com$
33.44.55.66/22
...
[proxy_list]
(^|\.)b\.com$
44.55.66.77/22
...
```
Is it right?

**Comment by madeye** [comment]
Nope, it's not supported in shadowsocks-android.

**Comment by Mygod** [comment]
In shadowsocks-android, custom rules are intended to extend the feature of GFW list and `bypass_all` mode is default and enforced. The matching basically works as follows:

1. If remote is hostname and it matches any pattern in `proxy_list`/`bypass_list`, it's proxied/bypassed, terminate;
2. If remote is hostname and it doesn't match any pattern, it's then resolved remotely to an IP address;
3. If the IP address matches any subnet in `proxy_list`, it's proxied, otherwise it's bypassed. The end.

Remark:
1. As you can tell subnets in `bypass_list` is not used. In fact, they will be discarded in shadowsocks-android while parsing the remote ACL;
2. If you insist to use `proxy_all` in your remote ACL, not only won't that work, but subnets in `bypass_list` are also discarded since they are not supposed to make a difference;
3. Protip: remote ACL is currently the only way to add hostname patterns to `proxy_list`.

@madeye Maybe we should add this to FAQ.

**Comment by madeye** [comment]
AFAIK, only `[proxy_list]` is supported in shadowsocks-android.

**Comment by Mygod** [comment]
@madeye is right. In that case I should update my implementation of Acl.kt. :sweat_smile:
