### ISSUE TITLE
Navigation Bar : Back to black

### ISSUE THREAD

**Issue by 967018** [shadowsocks/shadowsocks-android#1537]
Related passage: [Android's System Bars And Your Interface - Whether And How To Theme](http://www.androidpolice.com/2015/04/25/androids-system-bars-and-your-interface-whether-and-how-to-theme/)

---
## Reply to the issue #1520 :
Obvious though the status panel exists, what about the cases like "The drawer was pulled out" or performance on a tablet.

![screenshot_20171222-222101](https://user-images.githubusercontent.com/8299251/34439530-9d4760dc-ece9-11e7-9b1f-9f52b096798f.png)

![screenshot_20171229-224522](https://user-images.githubusercontent.com/8299251/34439613-19faac7e-ecea-11e7-916e-eeea12fd9a4d.png)

**"Immersive" doesn't exist anymore.**

---

## Problem:
Wrong usage of colouring navigation bar.

### Solution:

Reset to the default state. Black is just perfect.

## Why? 
As one of the [Principles](https://material.io/guidelines/#introduction-principles) "Bold, graphic, intentional" said:  

> The foundational elements of print-based design – typography, grids, space, scale, color, and use of imagery – guide visual treatments. These elements do far more than please the eye. They create **hierarchy**, **meaning**, and **focus**. **Deliberate color choices**, edge-to-edge imagery, large-scale typography, and intentional white space create a bold and graphic interface that **immerse the user in the experience**.

[Guideline's examples](https://material.io/guidelines/style/color.html#color-usability)

_Since the goal of colouring is to make the visual experience more immersive..._

### 1. Hierarchy & Focus: 

> Hierarchy refers to organizing content according to different levels of importance. Color can convey how important some content is relative to other content.

According to the literal meaning of System Bars, they are not part of the application, they are at a higher position than the application. Colouring them is an action to **ask** them cooperate with -- not to manipulating them cater -- the application.

> For example, a brightly colored button on a colorless background makes that button stand out. Alternatively, colorless bars and buttons allow bright content to take prominence in a UI.

Although I don't know the purpose of colouring the navigation bar with other colour in Shadowsocks, I'm clear that the meaning of colouring it with black -- **silence itself**. Black navigation bar lets users ignore it while they are using application, which makes the experience more immersive.

### 2. Meaning: 

> Color may be used to communicate the meaning of various elements on a screen.

Since the black navigation bar is humbleness, what's the meaning of coloured navigation bar in Shadowsocks?

**Comment by Mygod** [comment]
We need colored navigation bar for [this animation](https://github.com/shadowsocks/shadowsocks-android/commit/0335d67dba2f7367c537cbf5a81ecc37088ce1d2) to work.
![image](https://user-images.githubusercontent.com/3511321/34439865-0d237650-ecec-11e7-8bf3-00e327851314.png)

The examples you linked talk about coloring in general instead of the coloring of navigation bars.

1. I agree that black would look good if there hadn't been a status panel there. But since it's there, it actually has a symmetry feeling to it which in turns help hierarchy and focus.
2. Vibrancy.

P.S. Almost nobody uses Android tablets any more afaik.

At the end of the day, design is just a matter of opinion. For now I'd say we keep the colorful navigation bar.

**Comment by 967018** [comment]
@Mygod 

0. Could you explain why? (I couldn't read the code...)
1. However, those guidelines are universal. Is the colour on the navigation bar is not the colour?
2. The truth is, blue-grey will never be vibrant, blue-grey has "grey". And beauty is not the goal of design.

3. One of the goals of Material Design: 
> Develop a single underlying system that allows for a unified experience across platforms and **device sizes**.

4. May I ask you two question? Since Shadowsocks is free, what‘s your purpose of developing Shadowsocks? What do you think about Material Design?

**Comment by Mygod** [comment]
0. Why what?
1. See the link (it's from material.io so you know it's much more official and up-to-date than androidpolice.com) I posted in the previous issue that tackles specifically about navigation bar coloring schemes;
2. That's just your opinion. 😄 Blue-grey is still more vibrant than black.
3. I'll consider tablets if I have one;
4. Back in the days I developed it mainly for my personal use and as a pastime (I still do). Therefore I will accept anything that looks good to ME (yes it's highly subjective). And I push my changes to GitHub just because I'm very nice.

Thanks anyway for your suggestions. I may reconsider this in the future but for now I'm not planning to change it to black.

**Comment by 967018** [comment]
@Mygod 

0. I couldn't figure out why the animation requires a coloured navigation bar.
1. We confused each other. You mean the passage, I mean the "Guideline's examples".

1&2&3. These seem doesn't matter now. On the basis of 4--purpose, I got my ultimate answer.

It's lucky for Shadowsocks to has many contributors like you. I'll be moving forward to build a web-based design preview of Shadowsocks. Thank you for your patience and my unimpeded access to the Internet.

**Comment by Mygod** [comment]
Oh alright. For the animation, please wait for 4.4.3 to release.
