### ISSUE TITLE
How DNS options relate to each other?

### ISSUE THREAD

**Issue by initrider** [shadowsocks/shadowsocks-android#1555]
If I enable Forward DNS, it
* Will connect to DNS server, that set in Remote DNS setting (traffic to DNS server will go through shadowsocks) ?
* Will connect to DNS server, that set in Remote DNS setting (traffic to DNS server will NOT go through shadowsocks) ?
* Will connect to Local DNS server, that listens on port, that set in Local DNS Port setting. All requests to this port will be redirected to DNS server, that set in Remote DNS setting (traffic to Remote DNS server will go through shadowsocks) ?
* Will connect to Local DNS server, that listens on port, that set in Local DNS Port setting. All requests to this port will be redirected to DNS server, that set in Remote DNS setting (traffic to Remote DNS server will NOT go through shadowsocks) ?
* Will redirect all DNS requests to internal DNS resolver of Shadowsocks server?

Also, Local DNS Port will be UDP or TCP? Shadowsocks will connect to remote DNS server by UDP or TCP?
If I enable Forward DNS, will I able to use domain name as shadowsocks server adress? Remote DNS server adress? both shadowsocks and Remote DNS server adresses ?

**Comment by Mygod** [comment]
When DNS forwarding is enabled, all TCP/UDP DNS packets are treated as normal packets and forwarded directly to remote server regardless of route you pick. Local DNS port is not used. In case it's not clear, normally client app uses UDP DNS queries in which case a UDP request is sent to remote server.

When it's disabled, all TCP/UDP DNS packets are forwarded to local DNS port you picked which is then handled by overture. Those packets will either be queried locally or remotely via TCP based on route you pick. This option was originally called UDP forwarding since UDP may not be working under some conditions. Nowadays UDP forwarding is always enabled (so that you can use DNS routing and UDP applications like QUIC at the same time) and the only difference is how DNS packets are handled.

Remote DNS setting is always used (this was not the case in older version but it was eventually fixed). Internal DNS resolver of Shadowsocks server is used only if you connect to local SOCKS5 port manually and request a domain name.

You can always use domain name as shadowsocks server address which is always resolved locally. You should never use domain name as DNS server.

**Comment by Kein** [comment]
Hey, I will bump this question if you dont mind since I might be exceptionally dump but I'm failing to understand what purpose Local DNS port servers. If you enable UDP/DNS forwarding in the profile settings all DNS/UDP requests are send to the remove proxy server if it supports it (or send regardless if it doesnt and then fails, whatever). So what exactly happens if I disable Remote DNS in the profile? What role now Local DNS port plays? Because from what I see Shadowsocks client without Remote DNS enabled always uses local dns setup (resolv.conf or net.dns* properties or whatever it is in Android 9-10). What does the port do..?
