### ISSUE TITLE
Feature request: show an "Add to Apps VPN Mode" notification when a new app is installed

### ISSUE THREAD

**Issue by beta** [shadowsocks/shadowsocks-android#1635]
### Environment

* Android version: FreedomOS-op5-nevax-2.0.2 (Android 7.1.1)
* Device: OnePlus 5
* Shadowsocks version: v4.4.6

### Configuration

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: `aes-256-cfb`
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
  * Plugin: Simple obfuscation
  * Configure: `obfs-host=www.bing.com;obfs=http`
* [ ] Auto Connect
* [x] TCP Fast Open

### What did you do?

(Not applicable.)

### What did you expect to see?

When a new app is installed, show a notification or dialog to ask if the new app should be added into the _Apps VPN mode_ list of the current profile, as well as an _Add to All Profiles_ button.

Following is a screenshot of the Ice Box app for example, which is really convenient.

![image](https://user-images.githubusercontent.com/5000910/36190934-c8dd3480-1195-11e8-9581-dfd425d03bf8.png)

### What did you see instead?

Currently when I install a new app, I need to launch and turn off Shadowsocks, edit the current profile, enter _Apps VPN Mode_ section, find the newly installed app from a long list and save the profile. Usually I also need to use _Apply Settings to All Profiles_ in the menu to add the new app to all of my profiles.

**Comment by Mygod** [comment]
If you want to proxy new apps by default, use bypass mode. (and vice versa)

I personally don't find this proposal very useful.

**Comment by beta** [comment]
I tried bypass mode before, and that doesn't work for me either. As the apps I install are a mix of ones requiring proxy and ones that do not, chances are that I should enter the _Apps VPN Mode_ setting and pick the app from a long list of hundreds of apps installed on my phone, no matter it's in bypass mode or not.

Anyway thanks for the advice. This feature may only count particularly for me, and I will look into how to implement that myself.

**Comment by Mygod** [comment]
It'd be great if you could implement this feature. We might actually merge that if you implemented it. Some caveats:

* You can't listen for package changes using broadcast receivers in the manifest any more since [Android 8.0](https://developer.android.com/guide/components/broadcast-exceptions.html). Therefore the only reasonable thing to do if you want to implement this is to listen for package changes ONLY when VPN service is active. (please don't do `JobScheduler` and poll for package changes)
* VPN service needs to reload if you change the profile it's currently using; (the current implementation reloads profile before updating traffic stats and SQLite is process-safe so it should be fine)
* This notification could be bothersome so there had better be an option to turn it off. It's pretty darn easy to do this on Android 8+ using notification channel. Unfortunately this means we will have an additional option in the global settings for Android 7-. I'm not sure if @madeye likes that.

**Comment by beta** [comment]
Thank you for the info and that will be of great help to me. I will try to make some experiments and see if there could be somewhere better to put the notification settings when I have time during the holidays.

By the way, where can I find information regarding the capabilities and usage of the plugin mechanism? I'm wondering if the feature could be made as a plugin and installed on demand.

**Comment by Mygod** [comment]
Pretty outdated doc (nobody likes to write doc): https://github.com/shadowsocks/shadowsocks-android/blob/master/plugin/README.md

I'm afraid that's impossible. The plugin platform is meant for SIP003 plugins instead of automation.

**Comment by beta** [comment]
Okay I've found the [document](https://github.com/shadowsocks/shadowsocks-android/blob/master/plugin/README.md). I will have a look at it first.

**Comment by beta** [comment]
@Mygod Got it. I will then try to work on the code.
