### ISSUE TITLE
Feature Request: A widget (or on notification area) showing connection status of each server.

### ISSUE THREAD

**Issue by AndiMckee** [shadowsocks/shadowsocks-android#1647]
Now the situation of censorship in China is more severe, thus connection to server is banned from time to time. To keep connecting to OUTER network, I strongly request a new feature to solve this problem.
There are three ways that I have considered:

1. Auto connect to another available server when the present one is disconnected.
2. Show connection status of each server.
3. Send notification when the present server is disconnected.

**Comment by madeye** [comment]
No plan for this.

**Comment by Mygod** [comment]
This would involve possibly a large number of probes being sent somewhat periodically. This is problematic because:

1. This would possibly become a feature for detecting shadowsocks-android;
2. Unnecessary battery and bandwidth overhead, especially undesirable on metered networks.

Please find yourself a server that's stable enough instead. Connection test in this app is for diagnosis purpose only.
