### ISSUE TITLE
Please bring back NAT mode

### ISSUE THREAD

**Issue by Miegl** [shadowsocks/shadowsocks-android#1659]
I know that NAT mode is deprecated, however, I think it should be added back for the sake of option.
While the VPN mode works fine, Android allows only one VPN to be active at a time.
With NAT mode added back one could use a VPN app (for example Zerotier) and then use Shadowsocks to connect to the internet from a computer behind that VPN.
There is an app called ProxyDroid which does exactly this. However I prefer using Shadowsocks.

Please consider adding NAT mode back. Thanks.

**Comment by madeye** [comment]
Read the FAQ about the transparent proxy mode.

**Comment by Vinny24** [comment]
Anybody have Shadowsocks with NAT mode feature?
I am facing VPN issue in my Nougat ROM.

**Comment by aeroxy** [comment]
It looks like if I have my VPN turned on, I will not be able to add a Google account (aka sign in), likely due to some restriction on Google's services framework.

I have this suspicion because if I use NAT mode (not the Android VPN api) on my VPN apps, it would work (because then the system won't detect that I am using a VPN). Or if I use a router that connects to a VPN and it works as well.

I also notice if I am on my VPN, I often fail to visit Google Docs (I can open the App but not the docs), Play Store (I can see new apps but the "my app" page is forever loading and no request is made from visiting this page - the VPN apps can see how many packets sent), and Youtube (also forever loading on homepage with no packet sent). If this happen, I must remove the Google account, delete storage on Google Play Store, Play Services, and Partner Setup and re-add my Google account to get them working again.

This is rather inconvenient. But I am glad NAT mode is available on older shadowsocks, and it should be made the default VPN option since Google no longer works with `android.net.VpnService`.
