### ISSUE TITLE
Measurement Broker Service use too much memory

### ISSUE THREAD

**Issue by vovoa17** [shadowsocks/shadowsocks-android#1708]
When shadowsocks started, I found that the google play service was running in the background. I think this is not a bug. Does the developer have good suggestions?

Android 8.0
v4.5.2
![screenshot_20180325-205158](https://user-images.githubusercontent.com/29777681/38019587-970f3454-32aa-11e8-92ef-b1785605f1c4.png)

**Comment by madeye** [comment]
It's nothing to do with shadowsocks. Google Play service is shared by all the applications on your device.

**Comment by vovoa17** [comment]
All right.
By the way,can I change Overture's MinimumTTL value to optimize battery in mobile network?

Is the GCM heartbeat in the mobile network always 540 seconds?

**Comment by tony1016** [comment]
I use dnsmasq to control ttl,then use it as remote dns


在 2018年3月29日，下午4:48，vovoa17 <notifications@github.com> 写道：

All right.
By the way,can I change Overture's MinimumTTL value to optimize battery in
mobile network?

Is the GCM heartbeat in the mobile network always 540 seconds?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shadowsocks/shadowsocks-android/issues/1708#issuecomment-377167437>,
or mute the thread

**Comment by Mygod** [comment]
I wouldn't worry too much about it. I did a dumpsys and `MeasurementBrokerService` which is held by `com.google.android.gms` is bound to 10 different apps. It's showing up in Shadowsocks because Shadowsocks's VPN service is a foreground service and bound to system, and therefore it has the highest priority. If you turn off Shadowsocks, you should be able to observe that `com.google.android.gms` now appears under some other app's memory usage (for me it's Nova Launcher). Shadowsocks VPN service itself contributes a very moderate extra memory footprint (<<5MB) for this service and that 100MB is the total memory held by that process.
