### ISSUE TITLE
UDP Forward failure occurred when DNS Forwarding is turned off.

### ISSUE THREAD

**Issue by sqwwqw5** [shadowsocks/shadowsocks-android#2046]
I've been experiencing this issue for several months and finally figured it out.
Multiple games show the same results,[e.g.]:PUBG Mobile,FortNite.
When DNS Forwarding is turned off,the game disconnect from the game server instantly showing that UDP connection failed to be established.
When DNS Forwarding is turned on,games work perfectly.

Not sure if this is expected or otherwise maybe we can do some tricks to fix the issue.

**Comment by madeye** [comment]
1, Provide more information.
2. Run this app https://play.google.com/store/apps/details?id=md.tabuci.stunclient&hl=en_US and report the output here.

**Comment by sqwwqw5** [comment]
After spending an extending time I also confirmed that when the UDP Forwarding is enabled,it always shows the correct output with my server IP in the public IP section.
The issue seems only happened when UDP Forwarding is turned off.
All existing versions have this issue,the issue happened on all sorts of network conditions.(2G,LTE,Wifi)

**Comment by sqwwqw5** [comment]
edited*

**Comment by Oneeyear** [comment]
OK，thx




            
            
                
                    
                            
                                
                            
                            
                                pchmx
                            
                    
                        
                            
                                    邮箱：pchmx@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 12/27/2018 11:06, sqwwqw5 wrote: edited*

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shadowsocks/shadowsocks-android","title":"shadowsocks/shadowsocks-android","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/shadowsocks/shadowsocks-android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sqwwqw5 in #2046: edited*"}],"action":{"name":"View Issue","url":"https://github.com/shadowsocks/shadowsocks-android/issues/2046#issuecomment-450062942"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shadowsocks/shadowsocks-android/issues/2046#issuecomment-450062942",
"url": "https://github.com/shadowsocks/shadowsocks-android/issues/2046#issuecomment-450062942",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by madeye** [comment]
Make sure you're using the latest APKs here: https://github.com/shadowsocks/shadowsocks-android/releases/tag/v4.6.4

**Comment by sqwwqw5** [comment]
> Also try this APK: https://www.dropbox.com/s/5toqadvjqe469ex/mobile-universal-release-12-27.apk

The 12-27.apk simply makes the DNS Forwarding always enabled no matter the switch being turned on or off...
As I mentioned,no issue detected when DNS Forwarding enabled.

**Comment by sqwwqw5** [comment]
We don't want DNS Forwarding to be enabled due to the resolves of Chinese domains will be overseas IP addresses.
That leads to unnecessary proxy and potentially slow down.

**Comment by madeye** [comment]
Try "App proxy" and bypass the games, if you'd like to bypass UDP traffic.

**Comment by Mygod** [comment]
I'm not sure why you claim DNS forwarding is always enabled. When you disable DNS forwarding, only some of the DNS will be forwarded depending on your route.

**Comment by sqwwqw5** [comment]
> I'm not sure why you claim DNS forwarding is always enabled. When you disable DNS forwarding, only some of the DNS will be forwarded depending on your route.

That was a mistake,I switched to not bypass the Chinese IPs on that test.
Just ignore that comment,the rest remain the same.

**Comment by sqwwqw5** [comment]
12-27.apk is rather more complicated.
Instead of the output above,now it just shows UDP traffic is blocked(it's not),reconnect the node would put it back to work but minutes later it happens again.

**Comment by sqwwqw5** [comment]
After several hours of testing it is now safe to give the conclusion.
UDP Forward always works when DNS Forwarding is enabled.
With DNS Forwarding disabled,UDP Forward only works at the beginning of the connection but soon leads to fail.
It happened with different network carriers under different network conditions.

The goal is to play the game proxied while DNS Forwarding disabled.

**Comment by sqwwqw5** [comment]
For anyone want to test out this issue,you can use the app 'STU for NAT' mentioned above or any game that requires UDP connections.[e.g.]:Fortnite Android(just google it),PUBG Mobile(from play store).

**Comment by Oneeyear** [comment]
hey，bro，what is wrong with you，please do not send email to me again，thank you！




            
            
                
                    
                            
                                
                            
                            
                                pchmx
                            
                    
                        
                            
                                    邮箱：pchmx@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 12/27/2018 14:15, sqwwqw5 wrote: For anyone want to test out this issue,you can use the app 'STU for NAT' mentioned above or any game that requires UDP connections.[e.g.]:Fortnite Android(just google it),PUBG Mobile(from play store).

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shadowsocks/shadowsocks-android","title":"shadowsocks/shadowsocks-android","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/shadowsocks/shadowsocks-android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sqwwqw5 in #2046: For anyone want to test out this issue,you can use the app 'STU for NAT' mentioned above or any game that requires UDP connections.[e.g.]:Fortnite Android(just google it),PUBG Mobile(from play store)."}],"action":{"name":"View Issue","url":"https://github.com/shadowsocks/shadowsocks-android/issues/2046#issuecomment-450083564"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shadowsocks/shadowsocks-android/issues/2046#issuecomment-450083564",
"url": "https://github.com/shadowsocks/shadowsocks-android/issues/2046#issuecomment-450083564",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by madeye** [comment]
@sqwwqw5 Try again with this APK: https://www.dropbox.com/s/zbp4s4ldem92d0e/mobile-universal-release-udp-reuse.apk?dl=0

**Comment by sqwwqw5** [comment]
> @sqwwqw5 Try again with this APK: https://www.dropbox.com/s/zbp4s4ldem92d0e/mobile-universal-release-udp-reuse.apk?dl=0

@madeye 
What can I say?You nailed it!
But there's still something left behind.
After switching the network condition(say WIFI to LTE),UDP forward will be instantly blocked(at least that's what the app told me),reconnect the node would solve it.
I suggest this one is not related to the issue or the fix.

**Comment by sqwwqw5** [comment]
@

> BTW, as mentioned in [#2046 (comment)](https://github.com/shadowsocks/shadowsocks-android/issues/2046#issuecomment-450069311), if you just want to play mobile games that are based on UDP protocol, the best practice is using "Apps VPN Mode" and set it to bypass the selected apps there.

Thanks for the advice,I actually don't there's this mode existed.
Thus I still prefer a more transparent experience~

**Comment by sqwwqw5** [comment]
> > @sqwwqw5 Try again with this APK: https://www.dropbox.com/s/zbp4s4ldem92d0e/mobile-universal-release-udp-reuse.apk?dl=0
> 
> @madeye
> What can I say?You nailed it!
> But there's still something left behind.
> After switching the network condition(say WIFI to LTE),UDP forward will get instantly blocked(at least that's what the app told me)The state reamins even after switching back to WIFI again.
> Reconnect the node would solve it.
> I suggest this one is not related to the issue or the fix.

@madeye Hey,I checked several times that this other issue might just caused by the nature of CMCC-LTE block UDP traffics randomly,might not have nothing to do with ss-android.

Also the fix works quite well!Please merge the fix into the next release:)

**Comment by madeye** [comment]
Fixed via 8285109
