### ISSUE TITLE
Can not import profiles from json file.

### ISSUE THREAD

**Issue by evopen** [shadowsocks/shadowsocks-android#2069]
**Describe the bug**
profiles.json can not be selected from File. The file is greyed out.

**To Reproduce**
1. export profiles to profiles.json
2. import profiles from profiles.json

**Expected behavior**
able to select json file

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Lineage OS 16.0 nightly. Android Pie PQ1A.190105.004
 - Device: OnePlus 3T
 - Version: v4.6.5
 - Last version that did not exhibit the issue: [not applicable]

**Comment by Mygod** [comment]
You should be able to find MiXplorer from the drawer in the import process.

**Comment by evopen** [comment]
Ok. I missed that part. Sorry. Problem solved. 
But could this be done by using the built-in one? For example, org.isoron.uhabits pops up menu to let me choose which file manager to open backup file. And using the built-in one can open its .db backup file.

**Comment by Mygod** [comment]
Contributions are welcome.

**Comment by 4ft35t** [comment]
Same issues with nexus 5x，Android 8.1, opm7.181205.001, built-in Android Document.

**Comment by deamwork** [comment]
Android file management requires mime type to be correct so that application could read by certain file type.

[ProfilesFragment.kt](https://github.com/shadowsocks/shadowsocks-android/blob/master/mobile/src/main/java/com/github/shadowsocks/ProfilesFragment.kt#L383-L390) described the file that imported mime type **MUST** be `application/json`, which caused this issue.

```kotlin
            R.id.action_import_file -> {
                startFilesForResult(Intent(Intent.ACTION_GET_CONTENT).apply {
                    addCategory(Intent.CATEGORY_OPENABLE)
                    type = "application/json"
                    putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true)
                }, REQUEST_IMPORT_PROFILES)
                true
            }
```

Line 386 already told the system to filter files which mime type is `application/json`. So if you just "rename" a file to "file.json" will still won't work.

### Workaround:
For the android client, try not to designate file mime type specifically.
For the server who send this profile, set header as the following would help.

```text
Content-type: application/json; charset=utf-8
Content-Disposition: attachment;filename="profiles.json"
```

then you should able to import "profiles.json" to the app.

Personally, I recommended the second approach, which is more standardized for web application response.

**Comment by madeye** [comment]
@Mygod What do you think? As mentioned by @deamwork, we may not specify the file mime type here?

**Comment by Mygod** [comment]
Okay. Apparently Android MIME lookup doesn't support JSON type yet. I wonder what's the best way to do this.

Sources:

* https://stackoverflow.com/a/34402101/2245107
* https://android.googlesource.com/platform/libcore/+/master/luni/src/main/java/libcore/net/mime.types
* https://android.googlesource.com/platform/libcore/+/master/luni/src/main/java/libcore/net/android.mime.types

**Comment by nabilfreeman** [comment]
If you export even from within the Shadowsocks app and then try and import that file back in, it's greyed out. So I think you need to make at least some changes to the app, whether that's exporting profiles.json with correct MIME or making the import process smarter.

**Comment by deamwork** [comment]
@nabilfreeman 
Shadowsocks Android 4.6.5 (GooglePlay) can't reproduce your issue. Using Android 9, patch level 190105.

**Comment by 4ft35t** [comment]
Shadowsocks Android 4.6.5 (GooglePlay), nexus 5x, Android 8.1, opm7.181205.001 works fine now.
