### ISSUE TITLE
v4.8.0 cant use in vpn mode

### ISSUE THREAD

**Issue by TanY0Y0** [shadowsocks/shadowsocks-android#2229]
device: redmi k20,miui10.3.6
shadowsocks:v4.8.0

issue description:
i can use the same server config on windows client,iphone except my redmi.
it can link server as normal in vpn mode,but if you test it ,a few minutes later， it displays a error message.
it can test successful in the other two mode.
i tried many version as 4.5.x,4.6.x ,they also didnt work

![Screenshot_2019-06-03-16-27-37-274_com github sha](https://user-images.githubusercontent.com/51318636/58790666-6bad2f00-8623-11e9-9856-6ed1ad430d79.png)

**Comment by swjz** [comment]
I'm experiencing the exact same issue with OnePlus 5 on OxygenOS 4.5.10 (Android 7.1.1) and shadowsocks-android 4.7.4. It's interesting that I've been using shadowsocks-android on the same environment for years and it just happened to me recently. The issue server-dependent - I can have a server that works perfectly but another server having this issue after several days of daily use. I guess it might be due to some implementation difference between the VPN mode and other two modes, and a special feature or loophole in VPN mode is detected by GFW.

**Comment by swjz** [comment]
Rebooted and it's now working. Don't know if I was experiencing the same issue as OP's. Don't know how to reproduce the issue for now. Will update here when it occurs to me again.
