### ISSUE TITLE
battery drain caused by redsocks

### ISSUE THREAD

**Issue by jemyzhang** [shadowsocks/shadowsocks-android#227]
I found that the high CPU usage of redsocks may be the cause of battery drain on android 5.0.
![screenshot_2015-01-24-19-46-39](https://cloud.githubusercontent.com/assets/58111/5889724/b6bd7890-a470-11e4-976a-37b2c8b99abd.png)

**Comment by madeye** [comment]
NAT mode is not supported on Android 5.0 or above anymore.

**Comment by lepasserby** [comment]
Hello madeye!
I realize the issue is long since closed (so pardon me for... issue necromancy) but...
... could you provide a bit more details about nat mode not woring in Android 5.0+ (Google is not helping me)

Also, as to the whole battery drain issue, I've managed to find a device with both 4.0 and lolipop available and tested. 

So: 
 (a FLY phone, MTK 6589 ) and the battery drain on lolipop is pretty terrible. 
Also, deep sleep monitoring app reports that on Lolipop the device "sleeps" a little bit less (about 10% less) with shadowsocks.

Also compared 4.0 and 5.0 without shadowsocks, just naked 3G internet with some minimal stuff running (viber), lolipop does have bigger drain, but shadowsocks is almost two hours worse on lolipop, so there does seem to be some weird issue with shadowsocks here.

**Comment by lepasserby** [comment]
Hello @madeye!
I realize the issue is long since closed (so pardon me for... issue necromancy) but...
... could you provide a bit more details about nat mode not woring in Android 5.0+ (Google is not helping me)

Also, as to the whole battery drain issue, I've managed to find a device with both 4.0 and lolipop available and tested.

So:
(a FLY phone, MTK 6589 ) and the battery drain on lolipop is pretty terrible.
Also, deep sleep monitoring app reports that on Lolipop the device "sleeps" a little bit less (about 10% less) with shadowsocks.

Also compared 4.0 and 5.0 without shadowsocks, just naked 3G internet with some minimal stuff running (viber), lolipop does have bigger drain, but shadowsocks is almost two hours worse on lolipop, so there does seem to be some weird issue with shadowsocks here.
