### ISSUE TITLE
配置路由与测试节点

### ISSUE THREAD

**Issue by QCMorgan** [shadowsocks/shadowsocks-android#2313]
1.因为有多个服务器节点，默认路由为全局代理。如果将路由设置为绕过局域网与大陆，需要每一个节点依次修改，不能设置为所有节点的默认配置，添加代理应用时也是如此。希望添加此功能。
2.希望添加一键测试节点的功能。

**Comment by vcak** [comment]
Just try to translate this: 1) It is the full-field mode in routes' design by default. If you want to change to the mode of walking around the China mainland and LAN network, then it requires to modify one node by node inefficiently because normally you have gotten many server nodes globally.  So, hope to create a button like " apply to all Server Nodes" similar.   2) Hope to create a button like " one click  to verify all server nodes performance" similar.
