### ISSUE TITLE
Proposal: Calling `VpnService.protect` directly via JNI

### ISSUE THREAD

**Issue by zonyitoo** [shadowsocks/shadowsocks-android#2761]
**Is your feature request related to a problem? Please describe.**

shadowsocks-android and the underlying shadowsocks-rust are communicating via an UDS for protecting socket file descriptors by calling `VpnService.protect`, which is not elegant and causing some hard to reproduce problems.

**Describe the solution you'd like**

I got this idea from a Telegram Group. The original author have his copyright.

1. The `VpnService.protect` calls a C function [`protectFromVpn` in `NetdClient.h`](https://cs.android.com/android/platform/superproject/+/master:system/netd/include/NetdClient.h;l=37?q=protectFromVpn&sq=&ss=android%2Fplatform%2Fsuperproject) . Are there any chances that we can call this function directly? But the problem is how to link to `netd` when compiling.
2. Compile `sslocal` as a `.so` and expose two `start_local`, `stop_local` functions via JNI. When the `.so` is loaded, `JNI_OnLoad` will be called by JVM, then we can load the `Landroid/net/NetworkUtils`'s `protectFromVpn` function and then call it when creating outbound sockets.

**Describe alternatives you've considered**

No.

**Additional context**

No.

**Comment by zonyitoo** [comment]
The 2nd way should be practical, because:

1. Run `System.loadLibrary` on the compiled `.so` will call `JNI_OnLoad`.
2. Rust's [`jni`](https://crates.io/crates/jni) crate provides basic wrappers of JNI's structs.
3. Implementation details:
    - `start_local`: Create a `tokio::runtime::Runtime` and `spawn`s the `run_local` entry Future into it. Allocate a global *instance array* and find an empty slot for putting the `Runtime` in it. Returns the index of the slot as the instance ID.
    - `stop_local`: Accepts an instance ID and find the `Runtime` from the *instance array*, take it out and call `shutdown_backgroud` for killing the whole server.

**Comment by Mygod** [comment]
The API you proposed are not public API and I would advise against using it. Furthermore, `NetworkUtils.protectFromVpn` is blocked when targeting Android 12: https://developer.android.com/about/versions/12/non-sdk-12#new-blocked

Furthermore, in order to invoke a java method, you would first need to start up the JVM/`app_process` and then load Rust code as JNI. This creates huge memory overhead.

Finally, shadowsocks-android uses `Network.bindSocket` along with `ConnectivityManager` APIs to manage connection binding. `VpnService.protect` is only used for fallback.

See: https://github.com/shadowsocks/shadowsocks-android/blob/f5bc88b83ebbd4d2941a65bea2eaa565f2072db4/core/src/main/java/com/github/shadowsocks/bg/VpnService.kt#L77-L89

**Comment by Mygod** [comment]
As for your second solution, I think @madeye intentionally designed it to have separately running binaries.

**Comment by madeye** [comment]
I had a try years ago by using the JNI based `protect()` from golang: https://github.com/madeye/BaoLianDeng/blob/master/app/src/main/java/io/github/baoliandeng/core/LocalVpnService.java#L215

And as mentioned by @Mygod, the memory usage is huge... So I never did this in shadowsocks-android.

**Comment by nekohasekai** [comment]
> blocked when targeting Android 12

The blocked method is `protectFromVpn(FileDescriptor)` instead of `protectFromVpn(int)`.

![image](https://user-images.githubusercontent.com/56506714/125711339-da3b0f9b-6de2-412e-a4df-1af963bcb8c9.png)

In addition, this restriction [can be bypassed](http://lovesykun.cn/archives/android-hidden-api-bypass.html)

> uses Network.bindSocket

If you hate the non-standard usage, you can call your own callback method.

> the memory usage is huge

I don't think pure jni calls have "huge" memory usage, which could be a gomobile / memory leak problem.

---

In any case, you can also provide a setting to let the user choose which method to use.

**Comment by zonyitoo** [comment]
Maybe we don’t need to start a new JVM to load the Rust code, but instead to just call`System.loadLibrary` in the current process and then call the exposed APIs directly.

Are there any special reasons about using `app_manager` instead of `loadLibrary`? I am not familiar with Android dev.

**Comment by madeye** [comment]
First of all, `UDS` is not a problem. The entire Android system is based on `UDS` and we never see an issue is really caused by it in shadowsocks-android.

Secondly, the design choice here for shadowsocks-android is keeping every background service in different process. We'd like to avoid any 3rd party plugins to access the memory of the shadowsocks, to avoid any potential information leaks.
