### ISSUE TITLE
Seems [proxy_all] and [bypass_list} not working in custom ruls

### ISSUE THREAD

**Issue by iamsad3508** [shadowsocks/shadowsocks-android#2895]
### Discussed in https://github.com/shadowsocks/shadowsocks-android/discussions/2894

<div type='discussions-op-text'>

<sup>Originally posted by **iamsad3508** May 31, 2022</sup>
I want to bypass only 192.168.*.* with route set as ALL, but i know zero about rules, can anyone help?

</div>
Please read contributing guidelines. Thanks.

**Describe the bug**
Seems [proxy_all] and [bypass_list} not working in custom ruls

**To Reproduce**
SCENES 1
1. create an ACL file, fill it with
`[proxy_all]
[bypass_list]
192.168.0.0/16`
2. creat a url like https://abc.xyz/abc.acl
3. adding the url in custom rule-URL to onlifne config
4. change profile route to custom rules

SCENES 2
1. copy
`[proxy_all]
[bypass_list]
192.168.0.0/16`
2. open custom rules ,import from clipboard, FAIL TO IMPORT
Nothing show in the list and pop out a message : Fail to import
Seems including any of these(proxy_all and bypass_all) will fail to import

**Expected behavior**
SCENES 1 :all traffic including 127.0.0.1 go through SS, except 192.168.1.1
SCENES 2 :Import success

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 12 (SP2A.220505.002)
 - Device: Google Pixel 5
 - Version: 5.2.6 AND 5.2.6 nightly
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ X] IPv4 server address
* [ ] IPv6 server address
* [ X] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ X] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by yeganemehr** [comment]
same here!
I want to bypass some subnets, and proxy all others but it's not working

**Comment by Mygod** [comment]
Not supported.

**Comment by yeganemehr** [comment]
Such a shame!
We are living in a time that our governments take any action, pursuit any clue to shoot our access to free internet, to censor data flow.
You @Mygod and other contributors done wonderful job in this repo. Thank you!
But it's no need to this manner.
This issue is not big technical deal, All of code that do the job in there and it's important to people that using it.

You may heard in the news, In my country (Iran) now internet is shutdown and only domestic network is working.
Only essential services (like banks, online taxis, government services, etc) are working.
If you somehow could get access to global internet (with ssh tunneling through multiple hosts) you cannot access to those essential services; This isn't new, before these events all of important services in Iran just work in domestic network (Intranet) so we have to just keep switching VPNs on and off several times in a day (like 10-20 times in a day).

Do not forget why this projects exist, what was their philosophy.
You can solve this issue or at least keep it open to someday someone solve it.

-----------
For those like me that can't wait:  you can do this

1. First donwload apk of shadowsocks
```
cd /tmp
wget -O shadowsocks.apk https://github.com/shadowsocks/shadowsocks-android/releases/download/v5.2.6/shadowsocks--universal-v5.2.6.apk
```

2. Unpack apk of shadowsocks using [APKTool](https://github.com/iBotPeaches/Apktool)
```
apktool d -s shadowsocks.apk
```

3. Edit shadowsocks/assets/acl/gfwlist.acl to your desire.
4. Change value of  `route_entry_gfwlist` in shadowsocks/res/values/strings.xml
![Screenshot_2022-09-25_15-19-42](https://user-images.githubusercontent.com/16887332/192141920-398604c6-395b-4b68-8eca-84f559d1f972.png)

6. Repack apk
```
apk b shadowsocks
```

7. Generate a keystore:
```
keytool -genkey -keystore debug.keystore -validity 10000 -alias debug -keyalg rsa
```
8. Sign apk with your self-sign-certificate:
```
jarsigner -keystore debug.keystore -verbose shadowsocks/dist/shadowsocks.apk debug
```
9. Install it on your device:
```
adb install -r shadowsocks/dist/shadowsocks.apk
```
10. In your VPN profile, choose new option.
![photo_2022-09-25_15-22-18](https://user-images.githubusercontent.com/16887332/192142028-15fdbcf4-834b-4958-9d6d-d237691c83e6.jpg)

**Comment by fireinice** [comment]
The android client will automatically sync internal acl rules scheduled, as codes [core/src/main/java/com/github/shadowsocks/acl/AclSyncer.kt](https://github.com/shadowsocks/shadowsocks-android/blob/5a10078d23e930bb6f50de259d4e99ea00459bef/core/src/main/java/com/github/shadowsocks/acl/AclSyncer.kt#L35)

**Comment by fireinice** [comment]
> Such a shame! We are living in a time that our governments take any action, pursuit any clue to shoot our access to free internet, to censor data flow. You @Mygod and other contributors done wonderful job in this repo. Thank you! But it's no need to this manner. This issue is not big technical deal, All of code that do the job is there and it's important to people that using it.
> 
> You may heard in the news, In my country (Iran) now internet is shutdown and only domestic network is working. Only essential services (like banks, online taxis, government services, etc) are working. If you somehow could get access to global internet (with ssh tunneling through multiple hosts) you cannot access to those essential services; This isn't new, before these events all of important services in Iran just work in domestic network (Intranet) so we have to just keep switching VPNs on and off several times in a day (like 10-20 times in a day).
> 
> Do not forget why this projects exist, what was their philosophy. You can solve this issue or at least keep it open to someday someone solve it.
> 
> For those like me that can't wait: you can do this
> 
> 1. First donwload apk of shadowsocks
> 
> ```
> cd /tmp
> wget -O shadowsocks.apk https://github.com/shadowsocks/shadowsocks-android/releases/download/v5.2.6/shadowsocks--universal-v5.2.6.apk
> ```
> 
> 2. Unpack apk of shadowsocks using [APKTool](https://github.com/iBotPeaches/Apktool)
> 
> ```
> apktool d -s shadowsocks.apk
> ```
> 
> 3. Edit shadowsocks/assets/acl/gfwlist.acl to your desire.
> 4. Change value of  `route_entry_gfwlist` in shadowsocks/res/values/strings.xml
>    ![Screenshot_2022-09-25_15-19-42](https://user-images.githubusercontent.com/16887332/192141920-398604c6-395b-4b68-8eca-84f559d1f972.png)
> 5. Repack apk
> 
> ```
> apk b shadowsocks
> ```
> 
> 7. Generate a keystore:
> 
> ```
> keytool -genkey -keystore debug.keystore -validity 10000 -alias debug -keyalg rsa
> ```
> 
> 8. Sign apk with your self-sign-certificate:
> 
> ```
> jarsigner -keystore debug.keystore -verbose shadowsocks/dist/shadowsocks.apk debug
> ```
> 
> 9. Install it on your device:
> 
> ```
> adb install -r shadowsocks/dist/shadowsocks.apk
> ```
> 
> 10. In your VPN profile, choose new option.
>     ![photo_2022-09-25_15-22-18](https://user-images.githubusercontent.com/16887332/192142028-15fdbcf4-834b-4958-9d6d-d237691c83e6.jpg)

brilliant! but The android client will automatically sync internal acl rules scheduled, as codes [core/src/main/java/com/github/shadowsocks/acl/AclSyncer.kt](https://github.com/shadowsocks/shadowsocks-android/blob/5a10078d23e930bb6f50de259d4e99ea00459bef/core/src/main/java/com/github/shadowsocks/acl/AclSyncer.kt#L35)
The way need a custom dns like adguard to block shadowsocks.org ip resolve. otherwise the rule will substitute by the official acl rule in hours.
Better solution is add some feature as #2893
