### ISSUE TITLE
How to cancel domain name resolution on the client side before sending

### ISSUE THREAD

**Issue by yefangqingchen** [shadowsocks/shadowsocks-android#3153]
Why is the traffic through Shadowsocks only forwarded after the client resolves the domain name to IP? Can we cancel the process of obtaining and closing this?

**Comment by Mygod** [comment]
This app acts as a VPN service so the app handles all the DNS traffic. Cancelling DNS resolving in a client should be the same procedure as how you would do it without a VPN active.

**Comment by yefangqingchen** [comment]
I don't quite understand, so let me ask directly. Can we cancel or set the domain name not to resolve to IP before sending?

**Comment by yefangqingchen** [comment]
@Mygod 
I don't quite understand, so let me ask directly. Can we cancel or set the domain name not to resolve to IP before sending?

**Comment by pyang30** [comment]
I have the same question, according to [shadowsocks address protocal](https://shadowsocks.org/doc/what-is-shadowsocks.html#addressing), the address that client send to server follows [SOCKS5 address format](https://tools.ietf.org/html/rfc1928#section-5), 

The following address types are defined:

0x01: host is a 4-byte IPv4 address.
0x03: host is a variable length string, starting with a 1-byte length, followed by up to 255-byte domain name.
0x04: host is a 16-byte IPv6 address.

The port number is a 2-byte big-endian unsigned integer.

So, why does it need to perform DNS resolution before sending instead of sending the domain directly。
