### ISSUE TITLE
Android 6.0 下无法开机自启

### ISSUE THREAD

**Issue by agentmario** [shadowsocks/shadowsocks-android#380]
shadowsocks 版本 2.8.1, 设备是 Nexus 7 LTE, 更新 Android 6.0 之后程序无法随系统启动，望解决

**Comment by Kongloli** [comment]
设备是Nexus 5 系统也是Android 6.0，袜子版本也是2.8.1表示没问题。

**Comment by Halry** [comment]
我也一样无法自启,无论是stock还是modded的rom都是无法自启,勾已经打上,机器已root,用nat模式

**Comment by DeronLee** [comment]
Nexus 6 .6.0 開機自啟沒問題

**Comment by madeye** [comment]
@Halry NAT mode is no longer supported on Android 5.0+.

**Comment by dutonttie** [comment]
昨天线刷到android 6.0后，确实启动2.8.1时候报错，由于当时在英文版开google now所以一时忘了，今天升级到2.8.2后测试一下还是报错，我刚刚抓了个屏。
![screenshot_20151016-104212](https://cloud.githubusercontent.com/assets/9409003/10532687/c70246f6-73f3-11e5-888b-19ac1756e073.jpg)

**Comment by madeye** [comment]
@dutonttie NAT or VPN mode?

**Comment by dutonttie** [comment]
两者都一样的，我昨天就试过了。今天报错在vpn模式下。
2015年10月16日 10:55，"Max Lv" <notifications@github.com>写道：

**Comment by dutonttie** [comment]
有的人正常有的人出现问题，不知道是否和root有关系，由于当前root需要刷修改的内核的。

**Comment by madeye** [comment]
@dutonttie Right, it looks ROOT related. Maybe ROOT permission request on boot caused the crash on Android 6.0. I suggest to decline the ROOT permission of Shadowsocks in SuperSu and try again.

**Comment by wongsyrone** [comment]
Nexus 6 使用第三方内核配合supersu进行root一直没有出现问题

**Comment by dutonttie** [comment]
我在supersu里面禁用shadowsocks和删除shadowsocks条目，都是无法自动启动shadowsocks的。难道刷的内核不一样有关，楼上有刷第三方的正常的。我的内核是xda上面的hammerhead-mra58k-boot.zip 。

**Comment by wongsyrone** [comment]
我是N6的ElementX 3.02

**Comment by madeye** [comment]
@dutonttie You can post the logcat of crash here.

**Comment by Mygod** [comment]
Android 6.0, OnePlus One. Running smoothly here.

**Comment by dutonttie** [comment]
是这些吗？

--------- beginning of crash

10-16 11:24:32.985  3674  3674 E AndroidRuntime: FATAL EXCEPTION: main

10-16 11:24:32.985  3674  3674 E AndroidRuntime: Process: com.github.shadowsocks, PID: 3674

10-16 11:24:32.985  3674  3674 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.github.shadowsocks/com.github.shadowsocks.ShadowsocksRunnerActivity}: java.lang.IllegalStateException: Activity {com.github.shadowsocks/com.github.shadowsocks.ShadowsocksRunnerActivity} did not call finish() prior to onResume() completing

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Activity {com.github.shadowsocks/com.github.shadowsocks.ShadowsocksRunnerActivity} did not call finish() prior to onResume() completing

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6324)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)

10-16 11:24:32.985  3674  3674 E AndroidRuntime: 	... 10 more

10-16 11:24:33.692   834   922 I chatty  : uid=1000(system) AlarmManager expire 1 line

**Comment by madeye** [comment]
This is a bug in Android M developer preview. More details: https://code.google.com/p/android-developer-preview/issues/detail?id=2353

**Comment by dutonttie** [comment]
那一时半会没戏了，好在机器只在启动时候有问题。

**Comment by Mygod** [comment]
等等，似乎确实不能自启。

**Comment by madeye** [comment]
@dutonttie @Mygod Try this apk: https://dl.dropboxusercontent.com/u/4356689/shadowsocks-nightly-2.8.3.apk

**Comment by dutonttie** [comment]
还是不行，启动时候好像整个shadowsocks界面一闪而过，原来是跳出报错对话框。

**Comment by Mygod** [comment]
有个 activity 跳出来，但是没有连接。

**Comment by dutonttie** [comment]
怎么这么怪的，刚刚安装好首次不行，现在怎么两次又可以了，就是大窗口一闪好难看。我再试试，是否和第一次跳出supersu确认有关系。

**Comment by Kongloli** [comment]
Nexus5,Android6.0,Shadowsocks-Android2.8.1，也是开机就弹窗停止运行。

**Comment by dutonttie** [comment]
@Kongloli 不一样的，那个报错的窗口，后来那个是就是shadowsocks的主窗口。

**Comment by dutonttie** [comment]
这个是第一次没启动的日志：
10-16 14:51:15.070   834   834 W PackageManager: Unknown permission android.permission.ACCESS_SUPERUSER in package com.github.shadowsocks

10-16 14:51:15.838   834   924 W PackageManager: Unknown permission android.permission.ACCESS_SUPERUSER in package com.github.shadowsocks

10-16 14:51:44.979   834   845 I ActivityManager: Start proc 3736:com.github.shadowsocks/u0a85 for broadcast com.github.shadowsocks/.ShadowsocksReceiver

10-16 14:51:45.400   834   845 I ActivityManager: START u0 {flg=0x14000000 cmp=com.github.shadowsocks/.ShadowsocksRunnerActivity} from uid 10085 on display 0

10-16 14:51:45.584   834  1031 I ActivityManager: Start proc 3810:com.github.shadowsocks:vpn/u0a85 for service com.github.shadowsocks/.ShadowsocksVpnService

10-16 14:51:47.136   834  1476 I ActivityManager: Process com.github.shadowsocks:vpn (pid 3810) has died

10-16 14:51:47.137   834  1476 W ActivityManager: Scheduling restart of crashed service com.github.shadowsocks/.ShadowsocksVpnService in 1000ms

10-16 14:51:48.157   834   847 I ActivityManager: Start proc 4068:com.github.shadowsocks:vpn/u0a85 for service com.github.shadowsocks/.ShadowsocksVpnService

10-16 14:51:52.548   834   834 I ActivityManager: Killing 3736:com.github.shadowsocks/u0a85 (adj 15): empty #17

10-16 14:52:20.581   834  4392 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.shadowsocks/.Shadowsocks (has extras)} from uid 10027 on display 0

10-16 14:52:20.641   834   988 I ActivityManager: Start proc 4697:com.github.shadowsocks/u0a85 for activity com.github.shadowsocks/.Shadowsocks

**Comment by dutonttie** [comment]
我这边问题好像解决了，刚刚试了好多次，包括nat，vpn模式，都没法复制升级安装后第一次无法启动的问题了，都能正常启动。就是黑色的shadowsocks窗口会一闪，有点难看而已。

**Comment by madeye** [comment]
Try this one: https://dl.dropboxusercontent.com/u/4356689/shadowsocks-nightly-2.8.3-1.apk

**Comment by dutonttie** [comment]
问题解决了，谢谢～～！

**Comment by Halry** [comment]
在我的设备上运行是没有问题，就是不能自起，已root，用的是supersu 2.52，NAT模式正常。rom是chroma

**Comment by dutonttie** [comment]
说的就是不能自启问题，手工启动是正常的。

**Comment by Mygod** [comment]
我也能用。:-D

**Comment by dozer47528** [comment]
Nexus 5x 未 root
没办法自启动

另外在手机刚启动的时候，我手动点开启也没用。
过了几分钟后点才可以成功开启。

**Comment by haldong** [comment]
kernal4.4.4的miui7下 也不能开机自启~

**Comment by dozer47528** [comment]
我的 Nexus 5x ，什么都没动，却发现正常了，奇怪。

**Comment by Halry** [comment]
升级后就ok得了。
miui这种奇葩没办法，自己解决吧

**Comment by tttwwy** [comment]
开机自启,是否需要root?
